defaults: &defaults
  login:
    gmail:
      userid: <%= ENV['CONFIRM_EMAIL'] %>
      password: <%= ENV['CONFIRM_EMAIL_PASSWORD'] %>
    ohmyzip:
      userid: <%= ENV['OHMYZIP_USERID'] %>
      password: <%= ENV['OHMYZIP_PASSWORD'] %>

  email:
    gmail:
      address:
        amz_order_confirm: auto-confirm@amazon.com
        amz_shipping_confirm: ship-confirm@amazon.com
        package_tracker_confirm: notification.service.noreply@packagetrackr.com
      selector:
        amz_order_confirm: "h2 + a"
        amz_shipping_confirm: "span[style='font-size:12px;'] a"
        package_tracker_confirm: "td table tr:nth-child(2) td:nth-child(2)"
  webpage:
    ohmyzip:
      address:
        order_list: "http://www.ohmyzip.com/account/order_list.php?state=100"
        order_detail: "http://www.ohmyzip.com/account/order_detail.php?order_code="
      selector:
        order_list_row: ".tbl.tbl_border_grey tr"
        order_list_shipment_id: "a span"
        order_list_tracking_id: "a[href*=warpex]"
        order_detail_store: ".tbl_order tr:nth-child(3) td:nth-child(2)"
        order_detail_store_order_id: ".tbl_order tr:nth-child(4) td:nth-child(2)"
    warpex:
      address:
        tracking_page: "http://packing.warpex.com/api/warpexTrack?wbl="
      selector:
        status: "table tbody tr td:nth-child(2) img"
      status:
        step1: "/images/tracking/track_step1.gif"
        step2: "/images/tracking/track_step2.gif"
        step3: "/images/tracking/track_step3.gif"
        step4: "/images/tracking/track_step4.gif"
        step5: "/images/tracking/track_step5.gif"

test:
  <<: *defaults

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
